#
# Syntaxe correcte pour les versions récentes de Helix
#

[[language]]
name = "rust"
auto-format = true
# On déclare la liste des serveurs à utiliser pour ce langage
language-servers = [ "rust-analyzer" ]
indent = { tab-width = 4, unit = "    " }

# On configure ensuite chaque serveur de langage dans sa propre table
[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
# Utilise "clippy" pour le diagnostic.
check.command = "clippy"

# Active toutes les "features" du Cargo.toml.
cargo.allFeatures = true

# Indispensable pour l'autocomplétion des macros.
procMacro.enable = true

# Configuration des "inlay hints" (indications dans le code).
inlayHints.bindingModeHints.enable = true
inlayHints.chainingHints.enable = true
inlayHints.closingBraceHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.parameterHints.enable = true
inlayHints.typeHints.enable = true
inlayHints.typeHints.hideLessSpecificTypes = true
